[package]
name = "azumaneo"
version = "0.1.0"
authors = ["cloudybyte <hi@cloudybyte.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.1"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["macros", "signal", "sync"] }
pretty_env_logger = "0.3"
actix-rt = "1.0"
log = "0.4"
mongodb = { version = "1.1.1"}
bson = "1.1.0"
pbkdf2 = "0.6"
lazy_static = "1.4"
strum = "0.20.0"
strum_macros = "0.20"
term = "0.6.1"

# actix-http is needed for custom 404 response
# actix-http = "2.2.0"