[package]
name = "azumaneo"
version = "0.1.0"
authors = ["cloudybyte <hi@cloudybyte.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "^1.0"
actix-web = "^3.1"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "^1.4"
log = "0.4"
pretty_env_logger = "0.3"
rand = "0.7"
rust-argon2 = "0.8"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
sqlx = { version = "0.4", features = ["chrono", "macros", "migrate", "offline", "postgres", "runtime-actix-rustls", "uuid"] }
strum = { version = "0.20", features = ["derive"] }
term = "0.6"
tokio = { version = "0.2", features = ["macros", "signal", "sync"] }
uuid = { version = "0.8", features = ["serde"] }

# actix-http is needed for custom 404 response
# actix-http = "2.2.0"